# LOGGING
logging:
  file: logs/calc.log
  level:
    root: INFO
    ch.akros.cc.primecalculator: DEBUG
  pattern:
    file: '%d: %p [%c{8}] - %m%n'
    console: '%d: %p [%c{8}] - %m%n'

primecalc:
  begin: 2147483647
  end: 4294967294
  endpoint: http://localhost:666/calc